DB_CONNECTION=mysql
DB_HOST=148.72.63.136
DB_PORT=3306
DB_DATABASE=masrafji
DB_USERNAME=elsotaly
DB_PASSWORD=codecaique123


MAIL_DRIVER = smtp
MAIL_HOST = smtp.gmail.com
MAIL_PORT = 587
MAIL_USERNAME = mostafa hussien
MAIL_PASSWORD = MD13082021
MAIL_ENCRYPTION = null
MAIL_FROM_ADDRESS = moshus2407@gmail.com
MAIL_FROM_NAME = "${APP_NAME}"